[[redirects]]
from = "/fr.html"
to = "/fr"
status = 200

[[redirects]]
from = "/socketChat"
to = "https://socketchat0.herokuapp.com/"
status = 301
force = true

[[redirects]]
from = "/socketchat"
to = "https://socketchat0.herokuapp.com/"
status = 301
force = true

[[redirects]]
from = "/zipper"
to = "https://uofczipper.netlify.app/"
status = 200
force = true

[[redirects]]
from = "/resume"
to = "https://khanabdullah.com/assets/resume.pdf"
status = 200
force = true
